export const members = [
  {
    id: 1,
    memberId: '8934673327',
    dob: '20-11-1984',
    dos: '13-01-2022',
    npi: '8467382964',
    lastName: 'James',
    status: 'Rejected',
  },
  {
    id: 2,
    memberId: '9283745821',
    dob: '01-05-1990',
    dos: '25-10-2023',
    npi: '5647382928',
    lastName: 'Smith',
    status: 'Approved',
  },
  {
    id: 3,
    memberId: '8472637492',
    dob: '15-03-1985',
    dos: '10-12-2023',
    npi: '1029384756',
    lastName: 'Brown',
    status: 'Pending',
  },
  {
    id: 4,
    memberId: '4567284938',
    dob: '22-07-1992',
    dos: '09-09-2024',
    npi: '3827461927',
    lastName: 'Taylor',
    status: 'Rejected',
  },
  {
    id: 5,
    memberId: '8934673327',
    dob: '20-11-1984',
    dos: '13-01-2022',
    npi: '8467382964',
    lastName: 'James',
    status: 'Rejected',
  },
  {
    id: 6,
    memberId: '9283745821',
    dob: '01-05-1990',
    dos: '25-10-2023',
    npi: '5647382928',
    lastName: 'Smith',
    status: 'Approved',
  },
  {
    id: 7,
    memberId: '8472637492',
    dob: '15-03-1985',
    dos: '10-12-2023',
    npi: '1029384756',
    lastName: 'Brown',
    status: 'Pending',
  },
  {
    id: 8,
    memberId: '4567284938',
    dob: '22-07-1992',
    dos: '09-09-2024',
    npi: '3827461927',
    lastName: 'Taylor',
    status: 'Rejected',
  },
];
export const options = [
  { id: 1, name: 'Graspus graspus' },
  { id: 2, name: 'Grus rubicundus' },
  { id: 3, name: 'Speothos vanaticus' },
  { id: 4, name: 'Charadrius tricollaris' },
  { id: 5, name: 'Sciurus vulgaris' },
  { id: 6, name: 'Ateles paniscus' },
  { id: 7, name: 'Bucorvus leadbeateri' },
  { id: 8, name: 'Bubulcus ibis' },
  { id: 9, name: 'Physignathus cocincinus' },
  { id: 10, name: 'Phoca vitulina' },
  { id: 11, name: 'unavailable' },
  { id: 12, name: 'Zenaida galapagoensis' },
  { id: 13, name: 'Pseudalopex gymnocercus' },
  { id: 14, name: 'Terathopius ecaudatus' },
  { id: 15, name: 'Eumetopias jubatus' },
  { id: 16, name: 'Callorhinus ursinus' },
  { id: 17, name: 'Tamiasciurus hudsonicus' },
  { id: 18, name: 'Dasyurus viverrinus' },
  { id: 19, name: 'Madoqua kirkii' },
  { id: 20, name: 'Hystrix cristata' },
  { id: 21, name: 'Phalacrocorax niger' },
  { id: 22, name: 'Neotis denhami' },
  { id: 23, name: 'Conolophus subcristatus' },
  { id: 24, name: 'Cynictis penicillata' },
  { id: 25, name: 'Rhea americana' },
  { id: 26, name: 'Lama pacos' },
  { id: 27, name: 'Anitibyx armatus' },
  { id: 28, name: 'Motacilla aguimp' },
  { id: 29, name: 'Cereopsis novaehollandiae' },
  { id: 30, name: 'Anas platyrhynchos' },
  { id: 31, name: 'Varanus salvator' },
  { id: 32, name: 'Acanthaster planci' },
  { id: 33, name: 'Pelecanus occidentalis' },
  { id: 34, name: 'Pycnonotus nigricans' },
  { id: 35, name: 'Meles meles' },
  { id: 36, name: 'Anastomus oscitans' },
  { id: 37, name: 'Ardea cinerea' },
  { id: 38, name: 'Cereopsis novaehollandiae' },
  { id: 39, name: 'Butorides striatus' },
  { id: 40, name: 'Canis mesomelas' },
  { id: 41, name: 'Ephippiorhynchus mycteria' },
  { id: 42, name: 'Physignathus cocincinus' },
  { id: 43, name: 'Odocoileus hemionus' },
  { id: 44, name: 'Neotis denhami' },
  { id: 45, name: 'Theropithecus gelada' },
  { id: 46, name: 'Nycticorax nycticorax' },
  { id: 47, name: 'Theropithecus gelada' },
  { id: 48, name: 'Sarkidornis melanotos' },
  { id: 49, name: 'Conolophus subcristatus' },
  { id: 50, name: 'Anastomus oscitans' },
  { id: 51, name: 'Semnopithecus entellus' },
  { id: 52, name: 'Equus hemionus' },
  { id: 53, name: 'Phoenicopterus ruber' },
  { id: 54, name: 'Tyto novaehollandiae' },
  { id: 55, name: 'Canis aureus' },
  { id: 56, name: 'Haematopus ater' },
  { id: 57, name: 'Odocoilenaus virginianus' },
  { id: 58, name: 'Varanus sp.' },
  { id: 59, name: 'Crotalus triseriatus' },
  { id: 60, name: 'Vulpes chama' },
  { id: 61, name: 'Acrobates pygmaeus' },
  { id: 62, name: 'Myrmecophaga tridactyla' },
  { id: 63, name: 'Chlidonias leucopterus' },
  { id: 64, name: 'Elephas maximus bengalensis' },
  { id: 65, name: 'Lamprotornis nitens' },
  { id: 66, name: 'Francolinus swainsonii' },
  { id: 67, name: 'Trichosurus vulpecula' },
  { id: 68, name: 'Casmerodius albus' },
  { id: 69, name: 'Dusicyon thous' },
  { id: 70, name: 'Cracticus nigroagularis' },
  { id: 71, name: 'Corvus albicollis' },
  { id: 72, name: 'Giraffe camelopardalis' },
  { id: 73, name: 'Oryx gazella' },
  { id: 74, name: 'Cracticus nigroagularis' },
  { id: 75, name: 'Geococcyx californianus' },
  { id: 76, name: 'Litrocranius walleri' },
  { id: 77, name: 'Hystrix cristata' },
  { id: 78, name: 'Neophron percnopterus' },
  { id: 79, name: 'Boa caninus' },
  { id: 80, name: 'Lamprotornis superbus' },
  { id: 81, name: 'Tayassu pecari' },
  { id: 82, name: 'Branta canadensis' },
  { id: 83, name: 'Taurotagus oryx' },
  { id: 84, name: 'Tragelaphus scriptus' },
  { id: 85, name: 'Odocoileus hemionus' },
  { id: 86, name: 'Uraeginthus granatina' },
  { id: 87, name: 'Tenrec ecaudatus' },
  { id: 88, name: 'Bos taurus' },
  { id: 89, name: 'Cebus nigrivittatus' },
  { id: 90, name: 'Ciconia ciconia' },
  { id: 91, name: 'Canis lupus lycaon' },
  { id: 92, name: 'Canis aureus' },
  { id: 93, name: 'Corvus brachyrhynchos' },
  { id: 94, name: 'Cygnus atratus' },
  { id: 95, name: 'Platalea leucordia' },
  { id: 96, name: 'Dromaeus novaehollandiae' },
  { id: 97, name: 'Rhea americana' },
  { id: 98, name: 'Dusicyon thous' },
  { id: 99, name: 'Geochelone radiata' },
  { id: 100, name: 'Microcebus murinus' },
  { id: 191, name: 'Chlidonias leucopterus' },
  { id: 192, name: 'Macropus eugenii' },
  { id: 193, name: 'Vombatus ursinus' },
  { id: 194, name: 'Gopherus agassizii' },
  { id: 195, name: 'Morelia spilotes variegata' },
  { id: 196, name: 'Ateles paniscus' },
  { id: 197, name: 'Coracias caudata' },
  { id: 198, name: 'unavailable' },
  { id: 199, name: 'Cracticus nigroagularis' },
  { id: 200, name: 'Dasyurus viverrinus' },
  { id: 201, name: 'Chauna torquata' },
  { id: 202, name: 'Manouria emys' },
  { id: 203, name: 'Pituophis melanaleucus' },
  { id: 204, name: 'Macropus robustus' },
  { id: 205, name: 'Priodontes maximus' },
  { id: 206, name: 'Corvus albicollis' },
  { id: 207, name: 'Papilio canadensis' },
  { id: 208, name: 'Tachyglossus aculeatus' },
  { id: 209, name: 'Ardea cinerea' },
  { id: 210, name: 'Castor fiber' },
  { id: 211, name: 'Vanellus armatus' },
  { id: 212, name: 'Centrocercus urophasianus' },
  { id: 213, name: 'Boa constrictor mexicana' },
  { id: 214, name: 'Thylogale stigmatica' },
  { id: 215, name: 'Odocoileus hemionus' },
  { id: 216, name: 'Phoca vitulina' },
  { id: 217, name: 'Falco peregrinus' },
  { id: 218, name: 'Macropus rufogriseus' },
  { id: 219, name: 'Felis caracal' },
  { id: 220, name: 'Macropus fuliginosus' },
  { id: 221, name: 'Coluber constrictor' },
  { id: 222, name: 'Phalacrocorax brasilianus' },
  { id: 223, name: 'Ctenophorus ornatus' },
  { id: 224, name: 'Ara chloroptera' },
  { id: 225, name: 'Irania gutteralis' },
  { id: 226, name: 'Antidorcas marsupialis' },
  { id: 227, name: 'Capra ibex' },
  { id: 228, name: 'Ardea cinerea' },
  { id: 229, name: 'Lycosa godeffroyi' },
  { id: 230, name: 'Anser caerulescens' },
  { id: 231, name: 'Alcelaphus buselaphus caama' },
  { id: 232, name: 'Equus burchelli' },
  { id: 233, name: 'Otaria flavescens' },
  { id: 234, name: 'Canis lupus' },
  { id: 235, name: 'Pycnonotus barbatus' },
  { id: 236, name: 'Catharacta skua' },
  { id: 237, name: 'Myotis lucifugus' },
  { id: 238, name: 'Climacteris melanura' },
  { id: 239, name: 'Macropus rufogriseus' },
  { id: 240, name: 'Kobus leche robertsi' },
  { id: 241, name: 'Acrantophis madagascariensis' },
  { id: 242, name: 'Manouria emys' },
  { id: 243, name: 'Snycerus caffer' },
  { id: 244, name: 'Butorides striatus' },
  { id: 245, name: 'Acrobates pygmaeus' },
  { id: 246, name: 'Toxostoma curvirostre' },
  { id: 247, name: 'Cebus albifrons' },
  { id: 248, name: 'Zalophus californicus' },
  { id: 249, name: 'Herpestes javanicus' },
  { id: 250, name: 'Canis aureus' },
  { id: 251, name: 'Spilogale gracilis' },
  { id: 252, name: 'Macaca radiata' },
  { id: 253, name: 'Ursus americanus' },
  { id: 254, name: 'Crocodylus niloticus' },
  { id: 255, name: 'Bos taurus' },
  { id: 256, name: 'Coluber constrictor' },
  { id: 257, name: 'Anthropoides paradisea' },
  { id: 258, name: 'Boa caninus' },
  { id: 259, name: 'Axis axis' },
  { id: 260, name: 'Geochelone elephantopus' },
  { id: 261, name: 'Tamiasciurus hudsonicus' },
  { id: 262, name: 'Eubalaena australis' },
  { id: 263, name: 'Alectura lathami' },
  { id: 264, name: 'Zenaida asiatica' },
  { id: 265, name: 'Acrobates pygmaeus' },
  { id: 266, name: 'Choloepus hoffmani' },
  { id: 267, name: 'Ovis orientalis' },
  { id: 268, name: 'Dasypus novemcinctus' },
  { id: 269, name: 'Aonyx cinerea' },
  { id: 270, name: 'Melursus ursinus' },
  { id: 271, name: 'Cygnus buccinator' },
  { id: 272, name: 'Laniaurius atrococcineus' },
  { id: 273, name: 'Tetracerus quadricornis' },
  { id: 274, name: 'Lamprotornis nitens' },
  { id: 275, name: 'Perameles nasuta' },
  { id: 276, name: 'Equus hemionus' },
  { id: 277, name: 'Theropithecus gelada' },
  { id: 278, name: 'Ramphastos tucanus' },
  { id: 279, name: 'Mirounga leonina' },
  { id: 280, name: 'Ephippiorhynchus mycteria' },
  { id: 281, name: 'Falco peregrinus' },
  { id: 282, name: 'Cervus canadensis' },
  { id: 283, name: 'Mycteria leucocephala' },
  { id: 284, name: 'Eolophus roseicapillus' },
  { id: 285, name: 'Theropithecus gelada' },
  { id: 286, name: 'Halcyon smyrnesis' },
  { id: 287, name: 'Hymenolaimus malacorhynchus' },
];
export const jsonContent = {
  claims: [
    {
      accept_assign: 'Y',
      amount_paid: '98.75',
      auto_accident: 'N',
      auto_accident_state: '',
      bill_addr_1: '300 BILLINGSLEY RD',
      bill_addr_2: 'STE 200',
      bill_city: 'CHARLOTTE',
      bill_id: '',
      bill_name: 'CAROLINA DIGESTIVE HEALTH ASSOC',
      bill_npi: '1124052444',
      bill_phone: '7042413169',
      bill_state: 'NC',
      bill_taxid: '561335864',
      bill_taxid_type: 'E',
      bill_taxonomy: '',
      bill_zip: '282111075',
      charge: [
        {
          adj_amt_1: '1.52',
          adj_amt_2: '24.70',
          adj_code_1: 'C045',
          adj_code_2: 'PR2',
          charge: '125.00',
          chgid: '347461408',
          diag_ref: 'A',
          from_date: '2023-02-11',
          patient_responsibility: '24.70',
          place_of_service: '11',
          primary_paid_amount: '98.78',
          primary_paid_date: '2023-02-25',
          proc_code: 'J2357',
          remote_chgid: 'EP022519720558805-05',
          thru_date: '2023-02-11',
          units: '1',
        },
      ],
    },
  ],
};

export const jsonContent2 = {
  name: 'John Doe',
  age: 30,
  skills: ['JavaScript', 'React', 'Node.js'],
};
export const timelineData = [
  {
    icon: 'fa-file-alt',
    status: 'Claim Rejected',
    details: 'NPI Does not exist',
    date: 'Oct 19, 2024',
    statusColor: '#FF0F00',
  },
  {
    icon: 'fa-file-alt',
    status: 'Processed',
    details: 'To PACIFICSOURCE From ZELIS CLAIM 8371',
    date: 'Oct 17, 2024',
    statusColor: '#DC9D53',
  },
  {
    icon: 'fa-file-alt',
    status: 'Processed',
    details: 'From ZELIS CLAIM 8371',
    date: 'Oct 17, 2024',
    statusColor: '#DC9D53',
  },
  {
    icon: 'fa-file-alt',
    status: 'Processed',
    details: 'To ZELIS From PACIFICSOURCE CLAIM 8371',
    date: 'Oct 17, 2024',
    statusColor: '#DC9D53',
  },
  {
    icon: 'fa-file-alt',
    status: 'Received',
    details: 'From PACIFICSOURCE CLAIM 8371',
    date: 'Oct 17, 2024',
    statusColor: '#6E39CB',
  },
];
